### ISSUE TITLE
accessing database without password

### ISSUE THREAD

**Issue by sdepold** [sidorares/nodejs-mysql-native#9]
I'd like to see support for non-password-login. Setting no password always gives me:

{ field_count: 255
, errno: 1045
, message: 'Access denied for user \'root\'@\'localhost\' (using password: YES)'
}

**Comment by sidorares** [comment]
should work now
also you can connect now to local unix socket

**Comment by sdepold** [comment]
how do i use it now?

connection.auth('db', "root") ?
connection.auth('db', "root", null) ?

both don't work, still got , message: 'Access denied for user \'root\'@\'localhost\' (using password: YES)'

**Comment by sdepold** [comment]
using connection.auth('db', 'root', '') doesn't work as well but gives another error

node test.js

net:678
    throw new Error('Stream is not writable');
          ^
Error: Stream is not writable
    at Stream._writeOut (net:678:11)
    at Stream.write (net:664:17)
    at [object Object].write_packet (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/client.js:119:29)
    at cmd.write (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/commands.js:161:25)
    at cmd.start (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/commands.js:226:18)
    at cmd.process_packet (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/commands.js:144:43)
    at [object Object].dispatch_packet (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/client.js:126:37)
    at [object Object].dispatch_packet (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/client.js:130:22)
    at [object Object].dispatch_packet (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/client.js:130:22)
    at Stream.<anonymous> (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/client.js:172:28)
